name: Scrape latest puzzle from sudokuoftheday.com

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron:  '23 2 * * *' # 2:23 AM every day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Fetch latest puzzle
      run: |-
        uv run scripts/collect_training_data.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest puzzle: ${timestamp}" || exit 0
        git push