name: Unit tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.10'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@master

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}

    - name: Run unit tests
      run: |
        uv run pytest
  